name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn

      - name: Restore deps
        run: yarn install

      - name: Build extension
        run: yarn build
