name: CI

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore deps
        run: yarn install

      - name: Build and pack extension
        run: yarn build && yarn run pack

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dev-build
          path: |
            extension/**/*
            extension.*
